### ISSUE TITLE
An error occurred when fitting the model

### ISSUE THREAD

**Issue by prime51** [AlliedToasters/dfencoder#3]
When I'm trying to run the notebook, an error below occurs when hitting the `model.fit` line:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program Files (x86)\Anaconda\envs\torch\lib\site-packages\dfencoder\autoencoder.py", line 549, in fit
    self.build_model(df)
  File "D:\Program Files (x86)\Anaconda\envs\torch\lib\site-packages\dfencoder\autoencoder.py", line 339, in build_model
    self.init_features(df)
  File "D:\Program Files (x86)\Anaconda\envs\torch\lib\site-packages\dfencoder\autoencoder.py", line 245, in init_features
    self.init_cats(df)
  File "D:\Program Files (x86)\Anaconda\envs\torch\lib\site-packages\dfencoder\autoencoder.py", line 215, in init_cats
    objects = list(dt[dt==pd.Categorical].index)
  File "D:\Program Files (x86)\Anaconda\envs\torch\lib\site-packages\pandas\core\ops\common.py", line 64, in new_method
    return method(self, other)
  File "D:\Program Files (x86)\Anaconda\envs\torch\lib\site-packages\pandas\core\ops\__init__.py", line 529, in wrapper
    res_values = comparison_op(lvalues, rvalues, op)
  File "D:\Program Files (x86)\Anaconda\envs\torch\lib\site-packages\pandas\core\ops\array_ops.py", line 233, in comparison_op
    if len(lvalues) != len(rvalues):
TypeError: object of type 'type' has no len()

**Comment by prime51** [comment]
I solved this problem by explicitly making the type of categorical columns to pd.Categorical
